ExamInvigilatorProject/ExamInvigilatorProject/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExamInvigilatorProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExamInvigilatorProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Text;
using System.Security.Authentication;

namespace ExamInvigilatorProject.Pages
{
    public class LoginModel : PageModel
    {
        public bool success = false;
        public int attempts = 0;

        private readonly ILogger<LoginModel> _logger;

        public LoginModel(ILogger<LoginModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public RedirectToPageResult OnPostLogin()
        {
            dbEdit editor = new dbEdit();

            var emailAddress = Request.Form["loginemail"];          //needs sanitising to avoid sql injection
            var password = Request.Form["loginpassword"];           //needs sanitising to avoid sql injection



            bool found = editor.checkEmail(emailAddress);

            if (found)
            {
                string passwordHash = editor.getPasswordHash(emailAddress);
                byte[] passwordSalt = editor.getPasswordSalt(emailAddress);

                string saltedPassword = editor.hashPassword(password, passwordSalt);


                if (saltedPassword == passwordHash)
                {
                    // add cookie when signed in
                    editor.AddNewSession(editor.GetIdFromEmail(emailAddress), Response);

                    success = true;
                    string role = editor.getRole(emailAddress);

                    if (role == "INVIGILATOR")
                    {
                        return RedirectToPage("LoggedIn/Invigilator", "Start", new {id = editor.GetIdFromEmail(emailAddress)});
                        //Response.Redirect("LoggedIn/Invigilator");
                    }
                    else
                    {
                        //editor.logLogin(emailAddress);
                        return RedirectToPage("LoggedIn/Learner", "Start", new { id = editor.GetIdFromEmail(emailAddress) });
                        //Response.Redirect("LoggedIn/Learner");
                        //Student redirect.
                    }
                }
                else
                {
                    //login failed.
                    attempts += 1;
                    //need error message
                    //after 3 failed login attempts, link to forgot password/username page?
                }
            }
            attempts += 1;

            return RedirectToPage();
        }


    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExamInvigilatorProject.Pages
{
    public class RegisterModel : PageModel
    {

        public bool success = true;
        private readonly ILogger<RegisterModel> _logger;

        public RegisterModel(ILogger<RegisterModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
        public void OnPostRegister()
        {
            dbEdit editor = new dbEdit();
            var emailAddress = Request.Form["email"];
            var userpassword = Request.Form["userpassword"];
            var confirm = Request.Form["passwordConfirm"];
            var firstName = Request.Form["firstName"];
            var lastName = Request.Form["surname"];
            var roled = Request.Form["userType"];

            string role = "UNDEFINED";
            if (roled == "learner")
            {
                role = "LEARNER";
            }
            else if (roled == "invigilator")
            {
                role = "INVIGILATOR";
            }

            if (userpassword == confirm)
            {
                byte[] salt = editor.generateSalt();
                success = editor.register(emailAddress, firstName, lastName, userpassword, salt, role);
                Response.Redirect("/Login");
            }

        }


    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/WebcamTest.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExamInvigilatorProject.Pages
{
    public class WebcamTestModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/forgot.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Data.SqlClient;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Text;
using System.Security.Authentication;

namespace ExamInvigilatorProject.Pages
{
    public class forgotModel : PageModel
    {
        public bool success = false;
        public int attempts = 0;

        private readonly ILogger<forgotModel> _logger;

        public forgotModel(ILogger<forgotModel> logger)
        {
            _logger = logger;
        }

       
    }
}

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Highfield Education - Exam Invigilation Software ";
}

<head>
    <title>@ViewData["Title"] </title>

</head>

<body>
    <div class="mainContent">
        <h1>Remote Exam Invigilation</h1>
        <hr class="divider1"/>

        <div class="tableSection1">
            <img id="homePic" src="~/img/keyboard.png" alt="A pair of hands typing on a laptop keyboard">
        </div>
        <div class="tableSection2">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. 
            Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. 
            Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. 
            Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. </p>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.
                Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum.
                Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa.
                Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
            </p>
        
        </div>

</body>

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Highfield Education - Exam Invigilation Software Login </title>


</head>

<body>

    <div class="mainContent">
        <div class="login">
            <h1>@ViewData["Title"]</h1>
            
            <form asp-page-handler="login" method="post" autocomplete="off">

                @{
                    if (!Model.success && Model.attempts > 0)
                    {
                        <label for="loginemail"><i class="fas fa-envelope"></i></label>
                        <input type="email" name="loginemail" placeholder="Email or password are incorrect" id="loginemail" required>
                    }
                    else
                    {
                        <label for="loginemail"><i class="fas fa-envelope"></i></label>
                        <input type="email" name="loginemail" placeholder="Email" id="loginemail" required>
                    }

                }
                <label for="loginpassword"><i class="fas fa-lock"></i></label>
                <input type="password" name="loginpassword" placeholder="Password" id="loginpassword" required>


                <input type="submit" value="Login">


            </form>

        </div>
        <p id="forgot"><a href="/forgot">Forgot your password?</a></p>
    </div>


</body>

ExamInvigilatorProject/ExamInvigilatorProject/Pages/Register.cshtml
@page
@model RegisterModel
@{
    ViewData["Title"] = "Register";
}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Highfield Education - Exam Invigilation Software Login </title>


</head>

<body>
    <div class="mainContent">

        <div class="register">
            <form asp-page-handler="register" method="post" autocomplete="off">
                <select id="userType" name="userType">
                    <option value="learner">Choose Account Type</option>
                    <option value="learner">Learner</option>
                    <option value="invigilator">Invigilator</option>
                </select>


                <label for="firstName"><i class="fas fa-user"></i></label>
                <input type="text" name="firstname" placeholder="First Name" id="firstName" required>

                <label for="surname"><i class="fas fa-user"></i></label>
                <input type="text" name="surname" placeholder="Surname" id="surname" required>

                <!-- This code below changes the placeholder in the email box depending on wether the email entered has already been used.--->
                @if (Model.success)
                {
                    <label for="email"><i class="fas fa-envelope"></i></label>
                    <input type="email" name="email" placeholder="Email" id="" required>

                }
                else
                {
                    <label for="email"><i class="fas fa-envelope"></i></label>
                    <input type="email" name="email" placeholder="Email already in use!" id="email" required>
                }

                <label for="userpassword"><i class="fas fa-lock"></i></label>
                <input type="password" name="userpassword" placeholder="Password" id="userpassword" required>

                <label for="passwordConfirm"><i class="fas fa-lock"></i></label>
                <input type="password" name="passwordConfirm" placeholder="Confirm Password" id="passwordConfirm" required>

                @if (Model.success) {
                    <p id="regSuccess">Registration Successful - <a href="/Login">Login</a></p>
                }
                else
                {
                    <p id="regSuccess"></p>
                }

                <input type="submit" value="Register">
            </form>

        </div>

    </div>

</body>

ExamInvigilatorProject/ExamInvigilatorProject/Pages/WebcamTest.cshtml
@page
@model ExamInvigilatorProject.Pages.WebcamTestModel
@{
}

<head>
    <meta charset="utf-8" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="~/css/webcamtest.css" rel="stylesheet" />
</head>

<body>
<p>
    This example shows you the contents of the selected part of your
    display. Click the Start Capture button to begin.
</p>

<p>
    <button id="start">Start Capture</button>&nbsp;<button id="stop">
        Stop Capture
    </button>
</p>

<video id="video" autoplay></video>
<br />

<strong>Log:</strong>
<br />
<pre id="log"></pre>
<script src="~/js/webcamtest.js"></script>
</body>

ExamInvigilatorProject/ExamInvigilatorProject/Pages/forgot.cshtml
@page
@model forgotModel
@{
    ViewData["Title"] = "Forgot Login Details";
}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
    <div class="mainContent">
            <div class="login">
                <h1>I have forgotten my password</h1>
                <form asp-page-handler="login" method="post" autocomplete="off">
                    <label for="forgotEmail"><i class="fas fa-envelope"></i></label>
                    <input type="email" name="forgotEmail" placeholder="What's your email?">
                    <p>If your email is registered, you will be sent an email link to reset your password</p>
                    <input type="submit" value="Send">
                </form>
            </div>
      </div>
</body>